# Generated by Django 4.2.5 on 2023-09-18 10:36

from django.db import migrations, models
import testing_model_app.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_list', testing_model_app.custom_fields.IntegerListField(default=[])),
            ],
        ),
    ]
