# Generated by Django 4.2.5 on 2023-09-18 12:05

import circular_counter_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('counter', circular_counter_app.fields.CircularCounterField()),
            ],
        ),
    ]
