# Generated by Django 4.2.5 on 2023-09-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circular_counter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='number',
        ),
    ]
